# Generated by Django 2.2 on 2020-09-14 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalculadoraDeTroco',
        ),
    ]
